sudo: false

addons:
  chrome: stable

language: node_js

node_js:
  - "8.9.1"

before_install:
  - curl https://install.meteor.com/?release=1.6 | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
  - nohup sudo Xvfb :10 -ac
  - export DISPLAY=:10


cache:
  directories:
    - ~/.npm
    - "node_modules"

notifications:
  email: false

script:
  - meteor create --bare test
  - cd test
  - meteor npm i --save selenium-webdriver chromedriver
  - METEOR_PACKAGE_DIRS="../" TEST_BROWSER_DRIVER=chrome meteor --once test-packages --driver-package meteortesting:mocha ../